# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Configure and Reload Nginx
      - run: |
        if ! dpkg -s nginx > /dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y nginx
        fi
        if ! systemctl is-enabled nginx; then
            echo "Nginx is not enabled, Enabling Nginx"
            sudo systemctl enable nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Nginx is not running, Starting Nginx"
            sudo systemctl start nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Failed to start Nginx, exiting"
            exit 1
        fi
        echo "server {
            listen 80;
            server_name focus-pocus.ro;
            root /var/www/focus-pocus.ro/build;
            index index.html;
            location / {
                try_files $uri $uri/ =404;
            }
        }" | sudo tee /etc/nginx/sites-available/focus-pocus.ro.conf
        sudo sed -i 's/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
        if ! nginx -t; then
            echo "Nginx config test failed, correcting the config"
            sudo nginx -t -c /etc/nginx/nginx.conf
        fi
        echo "Reloading Nginx"
        sudo systemctl reload nginx

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Configure and Reload Nginx
      run: |
        if ! dpkg -s nginx > /dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y nginx
        fi
        if ! systemctl is-enabled nginx; then
            echo "Nginx is not enabled, Enabling Nginx"
            sudo systemctl enable nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Nginx is not running, Starting Nginx"
            sudo systemctl start nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Failed to start Nginx, exiting"
            exit 1
        fi
        echo "server {
            listen 80;
            server_name focus-pocus.ro;
            root /var/www/focus-pocus.ro/build;
            index index.html;
            location / {
                try_files $uri $uri/ =404;
            }
        }" | sudo tee /etc/nginx/sites-available/focus-pocus.ro.conf
        sudo sed -i 's/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
        if ! nginx -t; then
            echo "Nginx config test failed, correcting the config"
            sudo nginx -t -c /etc/nginx/nginx.conf
        fi
        echo "Reloading Nginx"
        sudo systemctl reload nginx
