# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Deploy

on:
  push:
    branches:
    - master

jobs:
  Setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Remove and Clone
      run: |
        if [ -d '/var/www/focus-pocus.ro' ]; then sudo rm -r /var/www/focus-pocus.ro; fi
        if [ ! -d '/var/www/focus-pocus.ro' ]; then sudo git clone https://github.com/CHINuit/focus-pocus.ro /var/www/focus-pocus.ro; fi
    - uses: actions/checkout@v3
    - name: Nodejs Install
      run: |
        if command -v node >/dev/null 2>&1; then
          echo "Node.js is already installed"
        else
          echo "Installing Node.js version 16"
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs;
        fi
    - uses: actions/checkout@v3
    - name: Npm Install
      run: |
        if command -v npm >/dev/null 2>&1; then
        echo "npm is already installed"
        else
        echo "Installing npm"
        sudo apt-get install npm -y
        fi
    - uses: actions/checkout@v3
    - name: Configure and Reload Nginx
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        if ! dpkg -s nginx > /dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y nginx
        fi
        if ! systemctl is-enabled nginx; then
            echo "Nginx is not enabled, Enabling Nginx"
            sudo systemctl enable nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Nginx is not running, Starting Nginx"
            sudo systemctl start nginx
        fi
        if ! systemctl is-active --quiet nginx; then
            echo "Failed to start Nginx, exiting"
            exit 1
        fi
        echo "server {
            listen 80;
            server_name focus-pocus.ro;
            return 301 'https://$server_name$request_uri';
            root /var/www/focus-pocus.ro/build;
            index index.html;
            location / {
                try_files $uri $uri/ =404;
            }
        }"" | sudo tee /etc/nginx/sites-available/focus-pocus.ro.conf
        sudo sed -i 's/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
        sudo cp /etc/nginx/sites-available/focus-pocus.ro.conf /etc/nginx/conf.d/
        sudo cp /etc/nginx/sites-available/focus-pocus.ro.conf /etc/nginx/sites-enabled/
        if [ -L /etc/nginx/sites-enabled/focus-pocus.ro.conf ]; then
        echo "Removing existing symbolic link"
         sudo rm -r /etc/nginx/sites-enabled/*
        fi
        echo "Creating symbolic link"
        sudo ln -s /etc/nginx/sites-available/focus-pocus.ro.conf /etc/nginx/sites-enabled

        if ! nginx -t; then
            echo "Nginx config test failed, correcting the config"
            sudo nginx -t -c /etc/nginx/nginx.conf
        fi
        echo "Reloading Nginx"
        sudo systemctl restart nginx
        sudo systemctl reload nginx
    - uses: actions/checkout@v3
    - name: CertBot
      run: |
        if sudo snap list certbot | grep -q "^certbot"; then
        echo "Certbot is already installed"
        else
        echo "Installing Certbot"
        sudo snap install --classic certbot
        sudo ln -s /snap/bin/certbot /usr/bin/certbot
        sudo certbot --nginx
        sudo certbot renew --dry-run
        fi

  
    #"finit": "cd /var/www/focus-pocus.ro && if ! git remote | grep -q 'focus-pocus.ro'; then sudo git remote add focus-pocus.ro https://github.com/CHINuit/focus-pocus.ro.git; fi",
    #"sync": "cd /var/www/focus-pocus.ro && sudo git config --global user.name --add Site && sudo git config --global user.email --add site@focus-pocus.ro && sudo git init && sudo git add . &&  sudo git commit --allow-empty -m 'synced' && sudo git stash save --keep-index && sudo git config --global pull.rebase false && sudo git pull -f origin master",
    #"clean": "if [ -f /var/www/focus-pocus.ro/package-lock.json ]; then sudo rm -r /var/www/focus-pocus.ro/package-lock.json; fi",
    #"clean2": "if [ -d /var/www/focus-pocus.ro/node_modules ]; then sudo rm -r /var/www/focus-pocus.ro/node_modules; fi",
    #"njsi": "cd /var/www/focus-pocus.ro && sudo npm install  --omit dev --save && sudo npm audit fix --force",
    #"bld": "sudo npm run start && sudo npm run build",    
